# Generated by Django 5.1.3 on 2024-11-26 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_town_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='town',
            field=models.CharField(choices=[('Kisumu', "K'Ogelo"), ('Nairobi', 'Rongai'), ('Mombasa', 'Nyali'), ('Kitale', 'Kajibroa'), ('Eldoret', 'Moiben'), ('Malindi', 'Tendawema'), ('Thika', 'Kiamaiko'), ('Nyeri', 'Mathira'), ('Nakuru', 'Njiru'), ('Garissa', 'Kainuk')], default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LS', 'Lassi'), ('PN', 'Paneer'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('MS', 'Milkshake'), ('CR', 'Curd'), ('GH', 'Ghee'), ('ML', 'Milk')], max_length=2),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
