# Generated by Django 5.1.3 on 2024-11-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer_town_alter_product_category_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='town',
            field=models.CharField(choices=[('Nairobi', 'Rongai'), ('Nakuru', 'Njiru'), ('Eldoret', 'Moiben'), ('Kisumu', "K'Ogelo"), ('Kitale', 'Kajibroa'), ('Nyeri', 'Mathira'), ('Mombasa', 'Nyali'), ('Garissa', 'Kainuk'), ('Malindi', 'Tendawema'), ('Thika', 'Kiamaiko')], default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('CZ', 'Cheese'), ('GH', 'Ghee'), ('CR', 'Curd'), ('ML', 'Milk'), ('MS', 'Milkshake'), ('LS', 'Lassi'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
