# Generated by Django 5.1.3 on 2024-11-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customer_town_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='town',
            field=models.CharField(choices=[('Thika', 'Kiamaiko'), ('Eldoret', 'Moiben'), ('Mombasa', 'Nyali'), ('Nakuru', 'Njiru'), ('Kitale', 'Kajibroa'), ('Kisumu', "K'Ogelo"), ('Malindi', 'Tendawema'), ('Nairobi', 'Rongai'), ('Nyeri', 'Mathira'), ('Garissa', 'Kainuk')], default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('IC', 'Ice-Creams'), ('ML', 'Milk'), ('CZ', 'Cheese'), ('GH', 'Ghee'), ('PN', 'Paneer'), ('LS', 'Lassi'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
