# Generated by Django 5.1.3 on 2024-12-02 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customer_town_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='town',
            field=models.CharField(choices=[('Thika', 'Kiamaiko'), ('Eldoret', 'Moiben'), ('Nyeri', 'Mathira'), ('Nakuru', 'Njiru'), ('Malindi', 'Tendawema'), ('Mombasa', 'Nyali'), ('Kitale', 'Kajibroa'), ('Garissa', 'Kainuk'), ('Nairobi', 'Rongai'), ('Kisumu', "K'Ogelo")], default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheese'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('ML', 'Milk'), ('CR', 'Curd')], max_length=2),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
