# Generated by Django 5.1.3 on 2024-12-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customer_town_alter_product_category_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='town',
            field=models.CharField(choices=[('Mombasa', 'Nyali'), ('Nairobi', 'Rongai'), ('Kisumu', "K'Ogelo"), ('Nyeri', 'Mathira'), ('Kitale', 'Kajibroa'), ('Garissa', 'Kainuk'), ('Malindi', 'Tendawema'), ('Thika', 'Kiamaiko'), ('Eldoret', 'Moiben'), ('Nakuru', 'Njiru')], default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('CZ', 'Cheese'), ('CR', 'Curd'), ('ML', 'Milk'), ('MS', 'Milkshake'), ('LS', 'Lassi'), ('PN', 'Paneer'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
